version: '3.0'
services:
  db:
    image: postgres:16.2-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    image: railsondocker_test
    build:
      context: .
      args:
        - PRECOMPILEASSETS=YES
    environment:
      - RAILS_ENV=test
      - APP_HOST=localhost
      - APP_PROTOCOL=http
    links:
      - db
    ports:
      - 3000:3000
